name: Build EXE
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write
jobs:
  build_and_test:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.13.0
      uses: actions/setup-python@v4
      with:
        python-version: 3.13.0
        architecture: 'x64'

    - name: Install Dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: main.exe
        path: dist/main.exe  # Ensure correct path
      
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: dist/main.exe
        tag_name: v1.0.${{ github.run_number }}
        name: Patrick v1.0.${{ github.run_number }}
        body: |
          Changes in this Release:
          - Added a new feature
          - Fixed a bug
          - Improved performance