name : Build EXE
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.13.0
      uses: actions/setup-python@v4
      with:
        python-version: 3.13.0
        architecture: 'x64'
    - name : Install Dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Build EXE
      run: |
        flet pack .\main.py

    - name : Rename the EXE File
      run: |
        Rename-Item -Path .\dist\main.exe -NewName "Patrick_v1.0.${{ github.run_number }}.exe"
      shell: powershell

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: Patrick_v1.0.${{ github.run_number }}.exe
        path: .\dist\Patrick_v1.0.${{ github.run_number }}.exe
        
      
    - name: Create Release
      uses: actions/create-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        release_name: Release v1.0.${{ github.run_number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        
